// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/access-menus": {
            "get": {
                "description": "Get list of application menus",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessMenus"
                ],
                "summary": "Get access menus",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AccessMenu"
                            }
                        }
                    }
                }
            }
        },
        "/access-menus/roles": {
            "get": {
                "description": "Get role-based menu access configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessMenus"
                ],
                "summary": "Get role access mappings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "description": "Update permission for a specific role and menu key (Admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AccessMenus"
                ],
                "summary": "Update role menu access",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "description": "Get authenticated user profile (Me)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserResponse"
                        }
                    }
                }
            }
        },
        "/cash-shifts/close": {
            "post": {
                "description": "Close active cashier shift (tutup kasir)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CashShifts"
                ],
                "summary": "Close cash shift",
                "parameters": [
                    {
                        "description": "Closing cash amount and notes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CloseCashShiftRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CloseCashShiftResponse"
                        }
                    }
                }
            }
        },
        "/cash-shifts/current": {
            "get": {
                "description": "Get active open cash shift for logged-in cashier",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CashShifts"
                ],
                "summary": "Get current cash shift",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CashShift"
                        }
                    }
                }
            }
        },
        "/cash-shifts/open": {
            "post": {
                "description": "Open a new cashier shift (buka kasir)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CashShifts"
                ],
                "summary": "Open cash shift",
                "parameters": [
                    {
                        "description": "Opening cash amount and notes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.OpenCashShiftRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.OpenCashShiftResponse"
                        }
                    }
                }
            }
        },
        "/finance/profit-loss": {
            "get": {
                "description": "Calculate total revenue, profit, and loss",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Get profit \u0026 loss summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/kitchen/orders": {
            "get": {
                "description": "Get list of active orders for kitchen display system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kitchen"
                ],
                "summary": "List active kitchen orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Order"
                            }
                        }
                    }
                }
            }
        },
        "/kitchen/orders/{id}/status": {
            "patch": {
                "description": "Update order status (preparing, ready, served, completed)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kitchen"
                ],
                "summary": "Update order status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New order status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateOrderStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/orders/checkout": {
            "post": {
                "description": "Process order checkout with idempotency key and stock deduction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Checkout order",
                "parameters": [
                    {
                        "description": "Checkout items and details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Order"
                        }
                    }
                }
            }
        },
        "/orders/history": {
            "get": {
                "description": "Get historical orders for financial reporting",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Finance"
                ],
                "summary": "Get order history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Order"
                            }
                        }
                    }
                }
            }
        },
        "/payments/charge": {
            "post": {
                "description": "Initiate payment charge (Midtrans QRIS / Snap)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Create payment charge",
                "parameters": [
                    {
                        "description": "Payment charge details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePaymentChargeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OrderPayment"
                        }
                    }
                }
            }
        },
        "/payments/order/{order_id}": {
            "get": {
                "description": "Get payment status and details by order ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Get payment by order ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "order_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OrderPayment"
                        }
                    }
                }
            }
        },
        "/payments/webhook": {
            "post": {
                "description": "Handle asynchronous payment status notification from Midtrans",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Midtrans payment webhook",
                "parameters": [
                    {
                        "description": "Webhook payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MidtransWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Get all products available in inventory",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "List all products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Product"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new product in inventory (Admin/Warehouse only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    }
                }
            }
        },
        "/products/{sku}": {
            "get": {
                "description": "Get specific product details by SKU",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get product by SKU",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product SKU",
                        "name": "sku",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    }
                }
            }
        },
        "/receipts/audits": {
            "get": {
                "description": "Get audit logs of scanned receipts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Receipts"
                ],
                "summary": "List receipt audits",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ReceiptAudit"
                            }
                        }
                    }
                }
            }
        },
        "/receipts/scan": {
            "post": {
                "description": "Extract item details from receipt image using AI vision client",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Receipts"
                ],
                "summary": "Scan receipt image (AI Vision)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Receipt Image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ReceiptAudit"
                        }
                    }
                }
            }
        },
        "/sync/status": {
            "get": {
                "description": "Check offline sync status and pending records count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sync"
                ],
                "summary": "Get sync status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/inbound.SyncStatusResponse"
                        }
                    }
                }
            }
        },
        "/sync/trigger": {
            "post": {
                "description": "Trigger data synchronization from local SQLite to central PostgreSQL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sync"
                ],
                "summary": "Trigger synchronization",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AccessMenu": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "domain.CashShift": {
            "type": "object",
            "properties": {
                "closed_at": {
                    "type": "string"
                },
                "closing_cash": {
                    "type": "number"
                },
                "expected_cash": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "opened_at": {
                    "type": "string"
                },
                "opening_cash": {
                    "type": "number"
                },
                "status": {
                    "description": "OPEN, CLOSED",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.CashShiftStatus"
                        }
                    ]
                },
                "total_cash_sales": {
                    "type": "number"
                },
                "total_debit_sales": {
                    "type": "number"
                },
                "total_qris_sales": {
                    "type": "number"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.CashShiftStatus": {
            "type": "string",
            "enum": [
                "OPEN",
                "CLOSED"
            ],
            "x-enum-varnames": [
                "CashShiftStatusOpen",
                "CashShiftStatusClosed"
            ]
        },
        "domain.OCRItem": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "domain.Order": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.OrderItem"
                    }
                },
                "status": {
                    "description": "PENDING, PREPARING, READY, SERVED, COMPLETED, CANCELLED, REFUNDED",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.OrderStatus"
                        }
                    ]
                },
                "total_amount": {
                    "type": "number"
                },
                "transaction_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.OrderItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "domain.OrderPayment": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "gateway": {
                    "$ref": "#/definitions/domain.PaymentGateway"
                },
                "gateway_transaction_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "payment_method": {
                    "$ref": "#/definitions/domain.PaymentMethod"
                },
                "raw_response": {
                    "type": "string"
                },
                "snap_redirect_url": {
                    "type": "string"
                },
                "snap_token": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.PaymentStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.OrderStatus": {
            "type": "string",
            "enum": [
                "UNPAID",
                "PENDING",
                "PREPARING",
                "READY",
                "SERVED",
                "COMPLETED",
                "CANCELLED",
                "EXPIRED",
                "REFUNDED",
                "PENDING",
                "COMPLETED",
                "CANCELLED",
                "REFUNDED"
            ],
            "x-enum-varnames": [
                "OrderStatusUnpaid",
                "OrderStatusPending",
                "OrderStatusPreparing",
                "OrderStatusReady",
                "OrderStatusServed",
                "OrderStatusCompleted",
                "OrderStatusCancelled",
                "OrderStatusExpired",
                "OrderStatusRefunded",
                "StatusPending",
                "StatusCompleted",
                "StatusCancelled",
                "StatusRefunded"
            ]
        },
        "domain.PaymentGateway": {
            "type": "string",
            "enum": [
                "MIDTRANS",
                "CASH"
            ],
            "x-enum-varnames": [
                "GatewayMidtrans",
                "GatewayCash"
            ]
        },
        "domain.PaymentMethod": {
            "type": "string",
            "enum": [
                "CASH",
                "MIDTRANS",
                "QRIS",
                "DEBIT"
            ],
            "x-enum-varnames": [
                "PaymentMethodCash",
                "PaymentMethodMidtrans",
                "PaymentMethodQris",
                "PaymentMethodDebit"
            ]
        },
        "domain.PaymentStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "SUCCESS",
                "FAILED",
                "EXPIRED"
            ],
            "x-enum-varnames": [
                "PaymentStatusPending",
                "PaymentStatusSuccess",
                "PaymentStatusFailed",
                "PaymentStatusExpired"
            ]
        },
        "domain.Product": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "sku": {
                    "type": "string"
                },
                "stock_quantity": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.ReceiptAudit": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "merchant_name": {
                    "type": "string"
                },
                "raw_ocr_json": {
                    "$ref": "#/definitions/domain.ReceiptOCRResult"
                },
                "receipt_date": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "domain.ReceiptOCRResult": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.OCRItem"
                    }
                },
                "merchant_name": {
                    "type": "string"
                },
                "total_amount": {
                    "type": "number"
                }
            }
        },
        "domain.UserRole": {
            "type": "string",
            "enum": [
                "ADMIN",
                "CASHIER",
                "KITCHEN",
                "WAREHOUSE"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleCashier",
                "RoleKitchen",
                "RoleWarehouse"
            ]
        },
        "dto.CheckoutItemRequest": {
            "type": "object",
            "required": [
                "quantity",
                "sku"
            ],
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "dto.CheckoutRequest": {
            "type": "object",
            "required": [
                "idempotency_key",
                "items"
            ],
            "properties": {
                "idempotency_key": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CheckoutItemRequest"
                    }
                },
                "payment_method": {
                    "$ref": "#/definitions/domain.PaymentMethod"
                }
            }
        },
        "dto.CloseCashShiftRequest": {
            "type": "object",
            "required": [
                "closing_cash"
            ],
            "properties": {
                "closing_cash": {
                    "type": "number",
                    "minimum": 0
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "dto.CloseCashShiftResponse": {
            "type": "object",
            "properties": {
                "closing_cash": {
                    "type": "number"
                },
                "difference": {
                    "type": "number"
                },
                "expected_cash": {
                    "type": "number"
                },
                "message": {
                    "type": "string"
                },
                "opening_cash": {
                    "type": "number"
                },
                "total_sales": {
                    "type": "number"
                }
            }
        },
        "dto.CreatePaymentChargeRequest": {
            "type": "object",
            "required": [
                "amount",
                "order_id"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "order_id": {
                    "type": "string"
                },
                "payment_method": {
                    "$ref": "#/definitions/domain.PaymentMethod"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponse"
                }
            }
        },
        "dto.MidtransWebhookRequest": {
            "type": "object",
            "required": [
                "order_id"
            ],
            "properties": {
                "gross_amount": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "signature_key": {
                    "type": "string"
                },
                "status_code": {
                    "type": "string"
                },
                "transaction_status": {
                    "type": "string"
                }
            }
        },
        "dto.OpenCashShiftRequest": {
            "type": "object",
            "required": [
                "opening_cash"
            ],
            "properties": {
                "notes": {
                    "type": "string"
                },
                "opening_cash": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "dto.OpenCashShiftResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "shift_id": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateOrderStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "enum": [
                        "PENDING",
                        "PREPARING",
                        "READY",
                        "SERVED",
                        "COMPLETED",
                        "CANCELLED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.OrderStatus"
                        }
                    ]
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.UserRole"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "inbound.SyncStatusResponse": {
            "type": "object",
            "properties": {
                "is_online": {
                    "type": "boolean"
                },
                "last_synced_at": {
                    "type": "string"
                },
                "pending_orders": {
                    "type": "integer"
                },
                "pending_payments": {
                    "type": "integer"
                },
                "pending_shifts": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
